Tela esqueci a senha corrigido
SAB-UFBA2022/frontend pull request #16
Opened 2022-09-28 04:30 UTC by boliveira12

# ✏📝 Descreva as mudanças que esse Pull Request implementa
### Descreva aqui

## O que esse PR representa?
- [X] Bug fix(mudança ininterrupta que corrige um problema) 🐞
- [ ] New Feature/Novo recurso (mudança ininterrupta que adiciona funcionalidade) ⚙
- [ ] Mudança de última hora (correção ou recurso que faria com que a funcionalidade existente não funcionasse conforme o esperado) ⏰
- [ ] Alteração de documentação 📝

# Checklist:

- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que meu recurso funciona 🧪
- [ ] Testes de unidade novos e existentes são aprovados localmente com minhas alterações 🧪
- [X] Meu código segue as diretrizes de estilo deste projeto 📏
- [ ] Realizei uma auto-revisão do meu próprio código 👨‍🏫👩‍🏫
- [ ] Removi arquivos inutilizados ♻
- [ ] Fiz as alterações correspondentes com a minha task 🙏
- [X ] Minhas alterações não geram novos problemas 🙏

2022-09-29 01:30 UTC, brunodelucasbarbosa requested changes

2022-09-29 01:30 UTC, brunodelucasbarbosa commented on src/components/ForgetPasswordForm/index.jsx
> +      await axios('/forgetpassword', {
Falta integrar isso ao back-end

2022-09-29 01:30 UTC, brunodelucasbarbosa commented on src/components/ForgetPasswordForm/index.jsx
> +        {successMessage && (
ver mensagem na linha 78

2022-09-29 01:30 UTC, brunodelucasbarbosa commented on src/components/ForgetPasswordForm/index.jsx
> +        {errorMessage && (
Isso aqui já da pra ser um componente, que inclusive acho que já existe....

2022-09-29 01:30 UTC, brunodelucasbarbosa commented on src/components/ForgetPasswordForm/index.jsx
> +          type="text"
Não há validação se realmente é um e-mail antes

![image](https://user-images.githubusercontent.com/60590932/192917747-c61af078-a8b2-414c-9162-9fde094c8130.png)

2022-09-29 01:30 UTC, brunodelucasbarbosa commented on src/pages/ForgetPassword/index.jsx
> +          Forneça seu endereço de e-mail usando durante o seu cadastro e enviaremos sua senha
Isso aqui precisa ser validado, pq não é assim que funciona no back-end, no protótipo diz algo, o front diz o que o protótipo diz, e o back funciona de outra forma

2022-09-29 01:30 UTC, brunodelucasbarbosa commented on src/components/ForgetPasswordForm/index.jsx
> +      await axios('/forgetpassword', {
Aproveitar e usar variavel de ambiente

2022-10-07 04:55 UTC, gabrielsoaresm94 commented on src/pages/ForgetPassword/index.jsx
> +          Forneça seu endereço de e-mail usando durante o seu cadastro e enviaremos sua senha
Olhei na api e vi que tinha uma requisição para mandar o email. Mantive assim.

2022-10-10 15:27 UTC, brunodelucasbarbosa commented
@boliveira12 @gabrielsoaresm94 tem conflitos na branch, precisa resolver

2022-10-24 17:16 UTC, lukedandrade approved these changes
Feature testada localmente e com emails já cadastrados/não cadastrados.
Para emails já cadastrados, uma nova senha foi gerada e enviada, permitindo o login com a nova senha.
Para emails não cadastrados, uma mensagem de erro é gerada e nada acontece.

2022-10-31 00:51 UTC, moniquedsilva commented
Adicionei detalhes que faltavam

2022-10-31 00:52 UTC, moniquedsilva approved these changes

2022-10-31 01:34 UTC, brunodelucasbarbosa approved these changes
@moniquedsilva

2022-10-31 01:36 UTC, merged